services:
  # 1. The Colyseus Backend
  - type: web
    name: colyseus-backend
    env: node
    plan: free
    # Notice: No rootDir here so Render can see /shared
    buildCommand: npm install && npm run build --workspace=server
    startCommand: npm start --workspace=server

  # 2. The Next.js Frontend
  - type: web
    # runtime: static
    name: nextjs-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build --workspace=client
    startCommand: npx serve@latest client/out --port 10000
    #staticPublishPath: app/client/out
    autoDeploy: false
