services:
  # 1. The Colyseus Backend
  - type: web
    name: colyseus-backend
    env: node
    plan: free
    # Notice: No rootDir here so Render can see /shared
    buildCommand: yarn install && yarn workspace @runebound-tactics/server build
    startCommand: yarn workspace @runebound-tactics/server start

#  # 2. The Next.js Frontend
#  - type: web
#    # runtime: static
#    name: nextjs-frontend
#    env: node
#    plan: free
#    buildCommand: yarn install && yarn workspace @runebound-tactics/client build
#    # Using npx serve to host the static output folder
#    startCommand: npx serve@latest client/out --listen $PORT    
#    autoDeploy: false
