import type { Metadata } from "next";
import { Pixelify_Sans, Jacquard_12, Tiny5 } from "next/font/google";
import "./globals.css";

const pixelify = Pixelify_Sans({
    variable: "--font-pixelify",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
    display: "swap",
});

const jacquard = Jacquard_12({
    variable: "--font-jacquard",
    subsets: ["latin"],
    weight: "400",
    display: "swap",
});

const tiny5 = Tiny5({
    variable: "--font-tiny5",
    subsets: ["latin"],
    weight: "400",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${pixelify.variable} ${jacquard.variable} ${tiny5.variable} h-full`}
            suppressHydrationWarning
        >
            <body className="min-h-full flex flex-col">{children}</body>
        </html>
    );
}
